-- Full schema baseline. Auth is handled by Supabase; no local users table.

-- ── Categories ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    name_en     VARCHAR(100) NOT NULL,
    parent_id   BIGINT REFERENCES categories(id),
    slug        VARCHAR(100) NOT NULL UNIQUE,
    icon        VARCHAR(50),
    sort_order  INT NOT NULL DEFAULT 0
);

-- ── Products ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS products (
    id               VARCHAR(36)      PRIMARY KEY,
    name             VARCHAR(500)     NOT NULL,
    normalized_name  VARCHAR(500)     NOT NULL,
    image_url        VARCHAR(2048),
    quantity_amount  DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    quantity_unit    VARCHAR(20)      NOT NULL DEFAULT 'stck',
    category_id      BIGINT REFERENCES categories(id),
    created_at       TIMESTAMP        NOT NULL,
    updated_at       TIMESTAMP        NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_products_normalized_name ON products(normalized_name);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);

CREATE TABLE IF NOT EXISTS rewe_products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id   VARCHAR(36)      NOT NULL REFERENCES products(id),
    rewe_id      VARCHAR(255)     NOT NULL UNIQUE,
    rewe_url     VARCHAR(2048),
    last_price   DOUBLE PRECISION,
    available    BOOLEAN          NOT NULL DEFAULT TRUE,
    last_updated TIMESTAMP        NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rewe_products_catalog ON rewe_products(catalog_id);

CREATE TABLE IF NOT EXISTS picnic_products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalog_id   VARCHAR(36)      NOT NULL REFERENCES products(id),
    picnic_id    VARCHAR(255)     NOT NULL UNIQUE,
    picnic_url   VARCHAR(2048),
    last_price   DOUBLE PRECISION,
    available    BOOLEAN          NOT NULL DEFAULT TRUE,
    last_updated TIMESTAMP        NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_picnic_products_catalog ON picnic_products(catalog_id);

CREATE TABLE IF NOT EXISTS product_tags (
    product_id VARCHAR(36)  NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    tag        VARCHAR(100) NOT NULL,
    PRIMARY KEY (product_id, tag)
);

CREATE INDEX IF NOT EXISTS idx_product_tags_tag ON product_tags(tag);

CREATE TABLE IF NOT EXISTS product_translations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term_en    VARCHAR(255) NOT NULL UNIQUE,
    term_de    VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

-- ── Carts ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    user_id    VARCHAR(36),
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255)  NOT NULL,
    quantity            DOUBLE        NOT NULL,
    unit                VARCHAR(50)   NOT NULL,
    product_id          VARCHAR(255),
    tags_filter         VARCHAR(1000),
    store_selections    TEXT,
    catalog_product_id  VARCHAR(36) REFERENCES products(id),
    cart_id             BIGINT        NOT NULL REFERENCES carts(id)
);

-- ── Favorites ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS favorites (
    id                 VARCHAR(255) PRIMARY KEY,
    user_id            VARCHAR(36)  NOT NULL,
    type               VARCHAR(50)  NOT NULL,
    product_id         VARCHAR(255),
    query              VARCHAR(1000),
    filter_tags        VARCHAR(1000),
    filter_volume      VARCHAR(100),
    filter_fat_content VARCHAR(100),
    filter_brand       VARCHAR(255),
    created_at         TIMESTAMP    NOT NULL
);

-- ── Picnic ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS picnic_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id    VARCHAR(255)  NOT NULL,
    auth_token   VARCHAR(2048),
    token_expiry BIGINT,
    updated_at   TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS picnic_connections (
    user_id      VARCHAR(36)   PRIMARY KEY,
    email        VARCHAR(255)  NOT NULL,
    auth_token   VARCHAR(2048) NOT NULL,
    token_expiry BIGINT,
    connected_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ── Seed: categories ──────────────────────────────────────────────────────────

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Obst & Gemüse',   'Produce',         NULL, 'produce',    'leaf',       1),

    ('Milch & Käse',    'Dairy',           NULL, 'dairy',      'milk',       2),
    ('Fleisch & Wurst', 'Meat & Deli',     NULL, 'meat',       'drumstick',  3),
    ('Bäckerei',        'Bakery',          NULL, 'bakery',     'bread',      4),
    ('Getränke',        'Drinks',          NULL, 'drinks',     'glass',      5),
    ('Tiefkühl',        'Frozen',          NULL, 'frozen',     'snowflake',  6),
    ('Fertiggerichte',  'Ready to Eat',    NULL, 'ready-to-eat','clock',     7),
    ('Grundnahrung',    'Pantry',          NULL, 'pantry',     'jar',        8),
    ('Frühstück',       'Breakfast',       NULL, 'breakfast',  'sun',        9),
    ('Süßes & Snacks',  'Sweets & Snacks', NULL, 'sweets',     'cookie',     10),
    ('Haushalt',        'Home',            NULL, 'home',       'house',      11),
    ('Baby & Kind',     'Baby & Child',    NULL, 'baby',       'baby',       12)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Obst',     'Fruits',     1, 'fruits',     NULL, 1),
    ('Gemüse',   'Vegetables', 1, 'vegetables', NULL, 2),
    ('Salate',   'Salads',     1, 'salads',     NULL, 3),
    ('Kräuter',  'Herbs',      1, 'herbs',      NULL, 4)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Milch',               'Milk',            2, 'milk',            NULL, 1),
    ('Käse',                'Cheese',          2, 'cheese',          NULL, 2),
    ('Joghurt',             'Yogurt',          2, 'yogurt',          NULL, 3),
    ('Butter & Margarine',  'Butter',          2, 'butter',          NULL, 4),
    ('Quark & Frischkäse',  'Cream Cheese',    2, 'cream-cheese',    NULL, 5),
    ('Eier',                'Eggs',            2, 'eggs',            NULL, 6),
    ('Sahne & Dessert',     'Cream & Dessert', 2, 'cream-dessert',   NULL, 7)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Rindfleisch',        'Beef',      3, 'beef',     NULL, 1),
    ('Hühnchen',           'Chicken',   3, 'chicken',  NULL, 2),
    ('Schweinefleisch',    'Pork',      3, 'pork',     NULL, 3),
    ('Wurst & Aufschnitt', 'Deli Meats',3, 'deli',     NULL, 4),
    ('Fisch & Meeresfrüchte','Seafood', 3, 'seafood',  NULL, 5)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Brot',           'Bread', 4, 'bread', NULL, 1),
    ('Brötchen',       'Rolls', 4, 'rolls', NULL, 2),
    ('Kuchen & Torten','Cakes', 4, 'cakes', NULL, 3)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Wasser',     'Water',       5, 'water',      NULL, 1),
    ('Säfte',      'Juices',      5, 'juices',     NULL, 2),
    ('Softdrinks', 'Soft Drinks', 5, 'soft-drinks',NULL, 3),
    ('Kaffee',     'Coffee',      5, 'coffee',     NULL, 4),
    ('Tee',        'Tea',         5, 'tea',        NULL, 5),
    ('Bier',       'Beer',        5, 'beer',       NULL, 6),
    ('Wein',       'Wine',        5, 'wine',       NULL, 7)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Tiefkühlkost', 'Frozen Foods', 6, 'frozen-foods', NULL, 1),
    ('Eis',          'Ice Cream',    6, 'ice-cream',    NULL, 2),
    ('Tiefkühlpizza','Frozen Pizza', 6, 'frozen-pizza', NULL, 3)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Nudeln & Reis',    'Pasta & Rice',   8, 'pasta-rice', NULL, 1),
    ('Mehl & Zucker',    'Flour & Sugar',  8, 'flour-sugar',NULL, 2),
    ('Öle & Essig',      'Oils & Vinegar', 8, 'oils',       NULL, 3),
    ('Konserven',        'Canned Goods',   8, 'canned',     NULL, 4),
    ('Gewürze & Saucen', 'Spices',         8, 'spices',     NULL, 5)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Müsli & Flocken',  'Cereals',    9, 'cereals',   NULL, 1),
    ('Marmelade & Honig','Jam & Honey', 9, 'jam',       NULL, 2),
    ('Aufschnitt',       'Cold Cuts',  9, 'cold-cuts', NULL, 3)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Schokolade', 'Chocolate', 10, 'chocolate', NULL, 1),
    ('Chips',      'Chips',     10, 'chips',     NULL, 2),
    ('Kekse',      'Cookies',   10, 'cookies',   NULL, 3)
ON CONFLICT DO NOTHING;

INSERT INTO categories (name, name_en, parent_id, slug, icon, sort_order) VALUES
    ('Reinigung',    'Cleaning',       11, 'cleaning',     NULL, 1),
    ('Papierwaren',  'Paper Products', 11, 'paper',        NULL, 2),
    ('Körperpflege', 'Personal Care',  11, 'personal-care',NULL, 3)
ON CONFLICT DO NOTHING;

-- ── Seed: translations ────────────────────────────────────────────────────────

INSERT INTO product_translations (term_en, term_de, created_at) VALUES
    ('milk',            'Milch',            NOW()),
    ('butter',          'Butter',           NOW()),
    ('eggs',            'Eier',             NOW()),
    ('egg',             'Eier',             NOW()),
    ('bread',           'Brot',             NOW()),
    ('yogurt',          'Joghurt',          NOW()),
    ('yoghurt',         'Joghurt',          NOW()),
    ('cheese',          'Käse',             NOW()),
    ('juice',           'Saft',             NOW()),
    ('water',           'Wasser',           NOW()),
    ('coffee',          'Kaffee',           NOW()),
    ('tea',             'Tee',              NOW()),
    ('flour',           'Mehl',             NOW()),
    ('sugar',           'Zucker',           NOW()),
    ('salt',            'Salz',             NOW()),
    ('oil',             'Öl',               NOW()),
    ('pasta',           'Nudeln',           NOW()),
    ('noodles',         'Nudeln',           NOW()),
    ('rice',            'Reis',             NOW()),
    ('tomatoes',        'Tomaten',          NOW()),
    ('tomato',          'Tomaten',          NOW()),
    ('potatoes',        'Kartoffeln',       NOW()),
    ('potato',          'Kartoffeln',       NOW()),
    ('onions',          'Zwiebeln',         NOW()),
    ('onion',           'Zwiebeln',         NOW()),
    ('apples',          'Äpfel',            NOW()),
    ('apple',           'Äpfel',            NOW()),
    ('bananas',         'Bananen',          NOW()),
    ('banana',          'Bananen',          NOW()),
    ('chicken',         'Hähnchen',         NOW()),
    ('beef',            'Rindfleisch',      NOW()),
    ('pork',            'Schweinefleisch',  NOW()),
    ('fish',            'Fisch',            NOW()),
    ('ham',             'Schinken',         NOW()),
    ('sausage',         'Wurst',            NOW()),
    ('cream',           'Sahne',            NOW()),
    ('sour cream',      'Saure Sahne',      NOW()),
    ('cottage cheese',  'Quark',            NOW()),
    ('pizza',           'Pizza',            NOW()),
    ('soup',            'Suppe',            NOW()),
    ('cereal',          'Müsli',            NOW()),
    ('cereals',         'Müsli',            NOW()),
    ('oats',            'Haferflocken',     NOW()),
    ('chocolate',       'Schokolade',       NOW()),
    ('chips',           'Chips',            NOW()),
    ('cookies',         'Kekse',            NOW()),
    ('biscuits',        'Kekse',            NOW()),
    ('jam',             'Marmelade',        NOW()),
    ('honey',           'Honig',            NOW()),
    ('wine',            'Wein',             NOW()),
    ('beer',            'Bier',             NOW()),
    ('water sparkling', 'Mineralwasser',    NOW()),
    ('sparkling water', 'Mineralwasser',    NOW()),
    ('orange juice',    'Orangensaft',      NOW()),
    ('apple juice',     'Apfelsaft',        NOW()),
    ('whole milk',      'Vollmilch',        NOW()),
    ('skim milk',       'Magermilch',       NOW()),
    ('low fat milk',    'Magermilch',       NOW()),
    ('cream cheese',    'Frischkäse',       NOW()),
    ('spaghetti',       'Spaghetti',        NOW()),
    ('tomato sauce',    'Tomatensauce',     NOW()),
    ('mustard',         'Senf',             NOW()),
    ('ketchup',         'Ketchup',          NOW()),
    ('mayonnaise',      'Mayonnaise',       NOW()),
    ('mayo',            'Mayonnaise',       NOW()),
    ('vinegar',         'Essig',            NOW()),
    ('garlic',          'Knoblauch',        NOW()),
    ('pepper',          'Pfeffer',          NOW()),
    ('paprika',         'Paprika',          NOW()),
    ('carrots',         'Karotten',         NOW()),
    ('carrot',          'Karotten',         NOW()),
    ('cucumber',        'Gurke',            NOW()),
    ('lettuce',         'Salat',            NOW()),
    ('spinach',         'Spinat',           NOW()),
    ('broccoli',        'Brokkoli',         NOW()),
    ('cauliflower',     'Blumenkohl',       NOW()),
    ('grapes',          'Trauben',          NOW()),
    ('strawberries',    'Erdbeeren',        NOW()),
    ('strawberry',      'Erdbeeren',        NOW()),
    ('orange',          'Orange',           NOW()),
    ('oranges',         'Orangen',          NOW()),
    ('lemon',           'Zitrone',          NOW()),
    ('lemons',          'Zitronen',         NOW()),
    ('pineapple',       'Ananas',           NOW()),
    ('mango',           'Mango',            NOW()),
    ('soap',            'Seife',            NOW()),
    ('shampoo',         'Shampoo',          NOW()),
    ('toilet paper',    'Toilettenpapier',  NOW()),
    ('tissues',         'Taschentücher',    NOW()),
    ('detergent',       'Waschmittel',      NOW()),
    ('dish soap',       'Spülmittel',       NOW()),
    ('frozen pizza',    'Tiefkühlpizza',    NOW()),
    ('ice cream',       'Eis',              NOW()),
    ('yogurt drink',    'Trinkjoghurt',     NOW()),
    ('milk drink',      'Milchgetränk',     NOW()),
    ('smoothie',        'Smoothie',         NOW())
ON CONFLICT DO NOTHING;
