-- Delivery fee rules per store, used as fallback when live API calls fail.

CREATE TABLE IF NOT EXISTS delivery_rules (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                 VARCHAR(50)      NOT NULL,
    min_basket_amount        DOUBLE PRECISION,
    max_basket_amount        DOUBLE PRECISION,
    delivery_fee             DOUBLE PRECISION NOT NULL,
    minimum_order_amount     DOUBLE PRECISION,
    free_delivery_threshold  DOUBLE PRECISION,
    note                     VARCHAR(255),
    created_at               TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_delivery_rules_store ON delivery_rules(store_id);

-- REWE delivery rules (Germany, current as of 2024)
-- minimum_order_amount is NULL: REWE has no minimum order, only a free-delivery threshold at €50.
INSERT INTO delivery_rules (store_id, min_basket_amount, max_basket_amount, delivery_fee, minimum_order_amount, free_delivery_threshold, note) VALUES
    ('rewe', 0.00,  49.99, 3.90, NULL, 50.00, 'Liefergebühr unter 50 €'),
    ('rewe', 50.00, NULL,  0.00, NULL, 50.00, 'Kostenlose Lieferung ab 50 €');

-- Picnic delivery rules (Germany, current as of 2024)
INSERT INTO delivery_rules (store_id, min_basket_amount, max_basket_amount, delivery_fee, minimum_order_amount, free_delivery_threshold, note) VALUES
    ('picnic', 0.00, NULL, 0.00, 35.00, 35.00, 'Kostenlose Lieferung ab 35 €');
