-- Schema for Shopping Planer — used by H2 (dev/test) and read by IntelliJ for JPA table resolution.
-- Production (PostgreSQL) schema is managed by Hibernate ddl-auto=update.

CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL UNIQUE,
    password_hash        VARCHAR(255) NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    role                 VARCHAR(50)  NOT NULL DEFAULT 'user',
    picnic_email         VARCHAR(255),
    picnic_auth_token    VARCHAR(2048),
    picnic_token_expiry  BIGINT,
    created_at           TIMESTAMP    NOT NULL,
    logged_out_at        TIMESTAMP
);

CREATE TABLE IF NOT EXISTS access_tokens (
    token       VARCHAR(255) PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    type        VARCHAR(50)  NOT NULL,
    expires_at  BIGINT       NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS carts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    user_id     BIGINT,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    quantity    DOUBLE       NOT NULL,
    unit        VARCHAR(50)  NOT NULL,
    product_id        VARCHAR(255),
    tags_filter       VARCHAR(1000),
    store_selections  TEXT,
    cart_id           BIGINT NOT NULL REFERENCES carts (id)
);

CREATE TABLE IF NOT EXISTS favorites (
    id                 VARCHAR(255) PRIMARY KEY,
    user_id            BIGINT       NOT NULL,
    type               VARCHAR(50)  NOT NULL,
    product_id         VARCHAR(255),
    query              VARCHAR(1000),
    filter_tags        VARCHAR(1000),
    filter_volume      VARCHAR(100),
    filter_fat_content VARCHAR(100),
    filter_brand       VARCHAR(255),
    created_at         TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS user_sessions (
    session_token     VARCHAR(255) PRIMARY KEY,
    picnic_auth_token VARCHAR(2048) NOT NULL,
    token_expiry      BIGINT,
    created_at        TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS picnic_sessions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id    VARCHAR(255)  NOT NULL,
    auth_token   VARCHAR(2048),
    token_expiry BIGINT,
    updated_at   TIMESTAMP     NOT NULL
);

CREATE TABLE IF NOT EXISTS delivery_rules (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id                 VARCHAR(50)      NOT NULL,
    min_basket_amount        DECIMAL(10,2),
    max_basket_amount        DECIMAL(10,2),
    delivery_fee             DECIMAL(10,2)    NOT NULL,
    minimum_order_amount     DECIMAL(10,2),
    free_delivery_threshold  DECIMAL(10,2),
    note                     VARCHAR(255),
    created_at               TIMESTAMP        NOT NULL DEFAULT CURRENT_TIMESTAMP
);

